ingresses:
  - ingressClass: alb
    annotations:
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:397599489272:certificate/96fe944e-ba80-41ef-93f2-2dc912254001
      alb.ingress.kubernetes.io/ssl-redirect: "443"
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/healthcheck-path: /ping
      alb.ingress.kubernetes.io/subnets: subnet-0cb3ac3401806157b, subnet-00f725c64e5f7fe04
    hosts:
      - host: api.test.com
        paths:
          - path: /
            service: private-api-ecosystem-nodeport
deployments:
  backends:
    private-api:
      config:
        AWS_REGION: us-east-1