images:
  proxy: nginxinc/nginx-unprivileged:1.23.3-alpine3.17

deployments:
  revisionHistoryLimit: 6
  backends:
    private-api:
      image: ghcr.io/ecosystem/ecosystem-private-api-backend:nil
      config: {}
      proxy:
        extraConfig: ""
      secrets: {}
      replicas:
        min: 1
        max: 2
      resources: {}
  workers: {}
config: {}
secrets: {}
affinity: {}

pullSecrets:
  - registry
