{{- range $name, $backend := .Values.deployments.backends }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v1

metadata:
  name: "{{ $.Release.Name }}-backend-{{ $name }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: "{{ $.Release.Name }}-backend-{{ $name }}"

  minReplicas: {{ $backend.replicas.min }}
  maxReplicas: {{ $backend.replicas.max }}

  targetCPUUtilizationPercentage: 90

---
{{- end }}