{{- range $name, $backend := .Values.deployments.backends }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-backend-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
type: Opaque
data:
{{- range $key, $val := $backend.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
---
# Check if $backend.volumes exists, if not, skip this part
{{- if $backend.secret_volumes }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-backend-{{ $name }}-secret-volumes
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
type: Opaque
data:
{{- range $key, $val := $backend.secret_volumes }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}

{{- end }}