{{- range $name, $worker := .Values.deployments.workers }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-worker-{{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
type: Opaque
data:
{{- range $key, $val := $worker.secrets }}
  {{ $key }}: {{ $val | b64enc | quote }}
{{- end }}
{{- end }}