kind: ConfigMap
apiVersion: v1

metadata:
  name: "{{ $.Release.Name }}"
  namespace: "{{ $.Release.Namespace }}"
  labels:
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
    app.kubernetes.io/component: common

data: 
  {{ toYaml $.Values.config | nindent 2 }}
