name: 'Plan'

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # # Checkout the base branch of the pull request (e.g. main/master).
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check out base ref
        run: |
          git fetch --no-tags --depth=1 origin $GITHUB_BASE_REF
          git fetch --no-tags --depth=1 origin $GITHUB_HEAD_REF

      - name: Get working directory
        run: |
          CODE_DIR=$(git --no-pager diff --diff-filter=d --raw --name-only origin/$GITHUB_BASE_REF origin/$GITHUB_HEAD_REF | egrep -E "\.tf\$|^\/test|^\/pre|^\/pro|^\/all" | grep ".*\/" -o | uniq)
          echo "WORKING_DIR=$CODE_DIR" >> $GITHUB_ENV

      # Generate Infracost JSON file as the baseline.
      - name: Generate Infracost cost estimate baseline
        id: infracost-baseline
        run: |
          mkdir -p ${{ env.WORKING_DIR }}
          touch ${{ env.WORKING_DIR }}main.tf
          infracost breakdown --path=${{ env.WORKING_DIR }} \
                              --format=json \
                              --out-file=/tmp/infracost-base.json \
                              --terraform-force-cli
      # Checkout the current PR branch so we can create a diff.
      - name: Checkout PR branch
        uses: actions/checkout@v3

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Infracost diff
        run: |
          infracost diff --path=${{ env.WORKING_DIR }} \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
          infracost output --path /tmp/infracost.json --format table --out-file /tmp/report.table

      - name: Post Infracost comment
        run: |
          infracost comment github --path /tmp/infracost.json \
          --repo $GITHUB_REPOSITORY \
          --github-token ${{ github.token }} \
          --pull-request ${{ github.event.pull_request.number }} \
          --behavior update